package consul

import "testing"
var ca = "  \n-----BEGIN CERTIFICATE-----\nMIIClTCCAhqgAwIBAgIUc0RcpY3GsV15cu/9g504t3hxXfswCgYIKoZIzj0EAwIw\ngYAxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwIU2hh\nbmdoYWkxDDAKBgNVBAoMA1dEUzEMMAoGA1UECwwDb3BzMQswCQYDVQQDDAJ0YzEi\nMCAGCSqGSIb3DQEJARYTMTU3MzY3NTUwNjdAMTYzLmNvbTAeFw0yMDAzMTkwOTM1\nNDBaFw0yMjEyMTQwOTM1NDBaMIGAMQswCQYDVQQGEwJDTjERMA8GA1UECAwIU2hh\nbmdoYWkxETAPBgNVBAcMCFNoYW5naGFpMQwwCgYDVQQKDANXRFMxDDAKBgNVBAsM\nA29wczELMAkGA1UEAwwCdGMxIjAgBgkqhkiG9w0BCQEWEzE1NzM2NzU1MDY3QDE2\nMy5jb20wdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAReNNTo2x+AtMee7XlwKreA6BHV\nLemahO2hEkPRUBYHkavmk384ilxU6wPq67XP8jci9aixlZJfuF6hoEf2ccvMCzLD\neCJBzrSq2tF84ui2zworf3ixK+FNIxYtpt/KFbOjUzBRMB0GA1UdDgQWBBTOV/p1\nigiwIZ0vFiZ01aQ2nHyTizAfBgNVHSMEGDAWgBTOV/p1igiwIZ0vFiZ01aQ2nHyT\nizAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA2kAMGYCMQC4Cdx4cMngpb7y\n2iQT8ZNuaKLd6j47r98fve+AT2Knh+uebPzKB4hbTpjN9pL7UswCMQCqMdu7NgYy\nZhkMnxlRFe/pQCytVzuMuc6TnukqwBzkx3QXaZedxLykN5Qij17iWG4=\n-----END CERTIFICATE-----"
func TestDockerCreateServiceConsul(t *testing.T) {
	r ,err := CreateServiceConsul("127.0.0.1", 8000,"test","ping", "grpc")
	if err != nil {
		t.Error(err)
	}
	r.ServiceRegister(nil)
}